DROP DATABASE IF EXISTS chatApp;

CREATE DATABASE IF NOT EXISTS chatApp;

USE chatApp;

CREATE TABLE IF NOT EXISTS Users(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(20) UNIQUE NOT NULL,
  hash VARCHAR(16) UNIQUE NOT NULL,
  salt VARCHAR(32) UNIQUE NOT NULL,
  cookies VARCHAR(16) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS Rooms(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(20) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS Messages(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  message TEXT NOT NULL,
  timestamp DATE NOT NULL,
  username varchar(20) NOT NULL,
  roomId INT,
  FOREIGN KEY (roomId) REFERENCES Rooms(id)
);

INSERT INTO Rooms (name) VALUES ('Lobby');